volumes:
    mysql_data:

services:
    sqldb:
        image: mysql:5.7
        container_name: helper-mysql
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
        command: --default-storage-engine innodb
        restart: unless-stopped
        healthcheck:
            test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3
    helper:
        image: mzkki/helper:latest
        container_name: helper-server
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=sqldb
            - DB_PORT=3306
            - DB_DATABASE=
            - DB_USERNAME=
            - DB_PASSWORD=
            - MAIL_MAILER=smtp
            - MAIL_HOST=
            - MAIL_PORT=
            - MAIL_USERNAME=
            - MAIL_PASSWORD=
            - MAIL_ENCRYPTION=null
            - GITHUB_ID=
            - GITHUB_SECRET=
            - GITHUB_URL=
        depends_on:
            - sqldb
        restart: "no"
        ports:
            - 8000:8000
        volumes:
            - /etc/localtime:/etc/localtime
    helper-queue:
        image: mzkki/helper:latest
        container_name: helper-queue
        depends_on:
            - helper
        restart: always
        command: php artisan queue:work
