version: "3.3"

volumes:
    mysql_data:

services:
    sqldb:
        image: mysql:5.7
        container_name: helper-mysql
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=project_management
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=passwordmysql123
            - MYSQL_ROOT_PASSWORD=passwordmysql123
        command: --default-storage-engine innodb
        restart: unless-stopped
        healthcheck:
            test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3
    helper:
        image: eloufirhatim/helper:latest
        container_name: helper-server
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=sqldb
            - DB_PORT=3306
            - DB_DATABASE=project_management
            - DB_USERNAME=dev
            - DB_PASSWORD=passwordmysql
            - MAIL_MAILER=smtp
            - MAIL_HOST=mail.binaanugerahsukses.com
            - MAIL_PORT=465
            - MAIL_USERNAME=siaga@mail.binaanugerahsukses.com
            - MAIL_PASSWORD=katasandiemail123
            - MAIL_ENCRYPTION=none
        depends_on:
            - sqldb
        restart: "no"
        ports:
            - 8000:8000
        volumes:
            - /etc/localtime:/etc/localtime
